In [6]:
import numpy as np
import pandas as pd

In [7]:
E = pd.read_csv("matrix_experiment.csv")
M = pd.read_csv("matrix_model.csv")
display(E, M)

   Fr  s  c  o
0   1  1  1  1
1  -1  1 -1  1
2   1 -1 -1  1
3  -1 -1  1  1
4   1  1  1 -1
5  -1  1 -1 -1
6   1 -1 -1 -1
7  -1 -1  1 -1

   Intercept  Fr  s  c  o  Fr:s  Fr:c  Fr:o  s:c  s:o  c:o
0        1.0   1  1  1  1     1     1     1    1    1    1
1        1.0  -1  1 -1  1    -1     1    -1   -1    1   -1
2        1.0   1 -1 -1  1    -1    -1     1    1   -1   -1
3        1.0  -1 -1  1  1     1    -1    -1   -1   -1    1
4        1.0   1  1  1 -1     1     1    -1    1   -1   -1
5        1.0  -1  1 -1 -1    -1     1     1   -1   -1    1
6        1.0   1 -1 -1 -1    -1    -1    -1    1    1    1
7        1.0  -1 -1  1 -1     1    -1     1   -1    1   -1